  package main

  import (
        "bufio"
        "encoding/csv"
        "fmt"
        "math/rand"
        "os"
        "path/filepath"
        "song-recognition/db"
        "song-recognition/shazam"
        "song-recognition/spotify"
        "song-recognition/wav"
        "strconv"
        "strings"
        "time"
  )

  const sqlBatchSize = 500

  const modeSQL    = "sql"
  const modeCSV    = "csv"
  const modeSQLite = "sqlite"

  func detectOutputMode(outputPath string) string {
        switch strings.ToLower(filepath.Ext(outputPath)) {
        case ".csv":
                return modeCSV
        case ".db", ".sqlite3":
                return modeSQLite
        default:
                return modeSQL
        }
  }

  func parseSongIDsFromCSV(csvPath string) ([]uint32, error) {
      f, err := os.Open(csvPath)
      if err != nil {
          return nil, err
      }
      defer f.Close()

      records, err := csv.NewReader(f).ReadAll()
      if err != nil {
          return nil, err
      }

      var ids []uint32
      for _, record := range records {
          if len(record) == 0 {
              continue
          }
          v, err := strconv.ParseUint(strings.TrimSpace(record[0]), 10, 32)
          if err != nil {
              continue // skip header or bad rows
          }
          ids = append(ids, uint32(v))
      }
      return ids, nil
  }

  func exportFingerprints(csvPath, outputPath, browser string, delaySeconds, jitterSeconds, maxRetries int) {
        f, err := os.Open(csvPath)
        if err != nil {
                fmt.Printf("Error opening CSV: %v\n", err)
                return
        }
        defer f.Close()

        reader := csv.NewReader(f)
        records, err := reader.ReadAll()
        if err != nil {
                fmt.Printf("Error reading CSV: %v\n", err)
                return
        }

        if len(records) == 0 {
                fmt.Println("CSV file is empty")
                return
        }

        // Skip header row if first field is non-numeric
        startIdx := 0
        if _, err := strconv.ParseUint(strings.TrimSpace(records[0][0]), 10, 32); err != nil {
                startIdx = 1
        }
        records = records[startIdx:]

        if len(records) == 0 {
                fmt.Println("No records to process")
                return
        }
        total := len(records)

        outputMode := detectOutputMode(outputPath)

        // SQLite mode: open DB client once, reuse across all songs
        var sqliteClient *db.SQLiteClient
        if outputMode == modeSQLite {
                sqliteClient, err = db.NewSQLiteClient(outputPath)
                if err != nil {
                        fmt.Printf("Error opening SQLite DB: %v\n", err)
                        return
                }
                defer sqliteClient.Close()
                fmt.Printf("Storing directly into SQLite: %s\n\n", outputPath)
        }

        // File-based output (SQL or CSV)
        var writer *bufio.Writer
        var csvWriter *csv.Writer
        if outputMode != modeSQLite {
                out, err := os.Create(outputPath)
                if err != nil {
                        fmt.Printf("Error creating output file: %v\n", err)
                        return
                }
                defer out.Close()

                writer = bufio.NewWriterSize(out, 1<<20)
                defer writer.Flush()

                if outputMode == modeCSV {
                        csvWriter = csv.NewWriter(writer)
                        csvWriter.Write([]string{"address", "anchorTimeMs", "songID"})
                } else {
                        fmt.Fprintf(writer, "-- Fingerprints export generated by seek-tune\n")
                        fmt.Fprintf(writer, "-- Generated: %s\n", time.Now().Format("2006-01-02 15:04:05"))
                        fmt.Fprintf(writer, "-- Total songs to process: %d\n\n", total)
                }
        }

	  unavailablePath := strings.TrimSuffix(outputPath, filepath.Ext(outputPath)) + "_unavailable.txt"
	  unavailableFile, err := os.OpenFile(unavailablePath, os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0644)
	  if err != nil {
	      fmt.Printf("Warning: could not create unavailable log: %v\n", err)
	      unavailableFile = nil
	  }
	  if unavailableFile != nil {
	      defer unavailableFile.Close()
	  }

        mainDB, err := db.NewDBClient()
        if err != nil {
                fmt.Printf("Warning: could not open main DB for skip check: %v\n", err)
                mainDB = nil
        } else {
                defer mainDB.Close()
        }

        successCount := 0
        errorCount := 0
        var lastDownloadTime time.Time

        for i, record := range records {
                if len(record) < 2 {
                        fmt.Printf("[%d/%d] Skipping invalid row\n", i+1, total)
                        errorCount++
                        continue
                }

                songIDStr := strings.TrimSpace(record[0])
                ytID := strings.TrimSpace(record[1])

                songIDInt, err := strconv.ParseUint(songIDStr, 10, 32)
                if err != nil {
                        fmt.Printf("[%d/%d] Invalid song_id '%s': %v\n", i+1, total, songIDStr, err)
                        errorCount++
                        continue
                }
                songID := uint32(songIDInt)
		  if sqliteClient != nil {
		      exists, err := sqliteClient.HasFingerprints(songID)
		      if err != nil {
			  fmt.Printf("[%d/%d] song_id=%-8s skipping (DB check error): %v\n", i+1, total, songIDStr, err)
			  errorCount++
			  continue
		      }
		      if exists {
			  fmt.Printf("[%d/%d] song_id=%-8s already fingerprinted, skipping\n", i+1, total, songIDStr)
			  successCount++
			  continue
		      }
		  }

		  if mainDB != nil {
		      exists, err := mainDB.HasFingerprints(songID)
		      if err == nil && exists {
			  fmt.Printf("[%d/%d] song_id=%-8s already in main DB, skipping\n", i+1, total, songIDStr)
			  successCount++
			  continue
		      }
		  }

                if !lastDownloadTime.IsZero() {
                        jitter := rand.Intn(jitterSeconds + 1)
                        target := time.Duration(delaySeconds+jitter) * time.Second
                        if elapsed := time.Since(lastDownloadTime); elapsed < target {
                                time.Sleep(target - elapsed)
                        }
                }
                lastDownloadTime = time.Now()

                fmt.Printf(
                        "[%d/%d] song_id=%-8s ytID=%-15s downloading...",
                        i+1, total, songIDStr, ytID,
                )

	  var audioPath string
	  var downloadErr error
	  for attempt := 0; attempt <= maxRetries; attempt++ {
	      if attempt > 0 {
		  backoff := time.Duration(1<<attempt) * time.Second
		  fmt.Printf(" retry %d/%d (backoff %v)...", attempt, maxRetries, backoff)
		  time.Sleep(backoff)
	      }
	      audioPath, downloadErr = spotify.DownloadByYTID(ytID, "tmp", browser)
	      if downloadErr == nil || downloadErr == spotify.ErrVideoUnavailable || downloadErr == spotify.ErrVideoNotAvailable || downloadErr == spotify.ErrPrivateVideo || downloadErr == spotify.ErrVideoViolation || downloadErr == spotify.ErrConfirmAge || downloadErr == spotify.ErrFormatNotAvailable {
		  break
	      }
	  }
	  if downloadErr == spotify.ErrVideoUnavailable || downloadErr == spotify.ErrVideoNotAvailable {
	      fmt.Printf(" SKIPPED (video unavailable)\n")
	      if unavailableFile != nil {
		  fmt.Fprintf(unavailableFile, "%s\n", songIDStr)
	      }
	      errorCount++
	      continue
	  }
	  if downloadErr == spotify.ErrPrivateVideo {
	      fmt.Printf(" SKIPPED (private video)\n")
	      if unavailableFile != nil {
		  fmt.Fprintf(unavailableFile, "%s\n", songIDStr)
	      }
	      errorCount++
	      continue
	  }	
	  if downloadErr == spotify.ErrVideoViolation {
	      fmt.Printf(" SKIPPED (video violating YouTube)\n")
	      if unavailableFile != nil {
		  fmt.Fprintf(unavailableFile, "%s\n", songIDStr)
	      }
	      errorCount++
	      continue
	  }		
	  if downloadErr == spotify.ErrConfirmAge {
	      fmt.Printf(" SKIPPED (confirm your age)\n")
	      if unavailableFile != nil {
		  fmt.Fprintf(unavailableFile, "%s\n", songIDStr)
	      }
	      errorCount++
	      continue
	  }
	  if downloadErr == spotify.ErrFormatNotAvailable {
	      fmt.Printf(" SKIPPED (format not available)\n")
	      if unavailableFile != nil {
		  fmt.Fprintf(unavailableFile, "%s\n", songIDStr)
	      }
	      errorCount++
	      continue
	  }	  
	  if downloadErr != nil {
	      fmt.Printf(" FAILED (download): %v\n", downloadErr)
	      errorCount++
	      continue
	  }

                if meta, metaErr := wav.GetMetadata(audioPath); metaErr == nil {
                        if durationSec, parseErr := strconv.ParseFloat(meta.Format.Duration, 64); parseErr == nil && durationSec > 600 {
                                os.Remove(audioPath)
                                fmt.Printf(" SKIPPED (duration %.0fs exceeds 10 min)\n", durationSec)
                                if unavailableFile != nil {
                                        fmt.Fprintf(unavailableFile, "%s\n", songIDStr)
                                }
                                errorCount++
                                continue
                        }
                }

                fmt.Print(" fingerprinting...")

                fingerprints, err := shazam.FingerprintAudio(audioPath, songID)
                os.Remove(audioPath)
                if err != nil {
                        fmt.Printf(" FAILED (fingerprint): %v\n", err)
                        errorCount++
                        continue
                }

                switch outputMode {
                case modeSQLite:
                        if err := sqliteClient.StoreFingerprints(fingerprints); err != nil {
                                fmt.Printf(" FAILED (store): %v\n", err)
                                errorCount++
                                continue
                        }

                case modeCSV:
                        for address, couple := range fingerprints {
                                csvWriter.Write([]string{
                                        strconv.FormatUint(uint64(address), 10),
                                        strconv.FormatUint(uint64(couple.AnchorTimeMs), 10),
                                        strconv.FormatUint(uint64(couple.SongID), 10),
                                })
                        }
                        csvWriter.Flush()

                default: // modeSQL
                        const insertPrefix = "INSERT OR REPLACE INTO fingerprints" +
                                " (address, anchorTimeMs, songID) VALUES "

                        fmt.Fprintf(
                                writer,
                                "-- song_id: %s  ytID: %s  fingerprints: %d\n",
                                songIDStr, ytID, len(fingerprints),
                        )
                        fmt.Fprintln(writer, "BEGIN;")

                        values := make([]string, 0, sqlBatchSize)
                        for address, couple := range fingerprints {
                                row := fmt.Sprintf(
                                        "(%d,%d,%d)",
                                        address, couple.AnchorTimeMs, couple.SongID,
                                )
                                values = append(values, row)
                                if len(values) == sqlBatchSize {
                                        fmt.Fprintf(writer, "%s%s;\n",
                                                insertPrefix, strings.Join(values, ","))
                                        values = values[:0]
                                }
                        }
                        if len(values) > 0 {
                                fmt.Fprintf(writer, "%s%s;\n",
                                        insertPrefix, strings.Join(values, ","))
                        }

                        fmt.Fprintln(writer, "COMMIT;")
                        fmt.Fprintln(writer)
                }

                fmt.Printf(" done (%d fingerprints)\n", len(fingerprints))
                successCount++
        }

        fmt.Printf("\nExport complete: %d succeeded, %d failed\n", successCount, errorCount)
        if outputMode != modeSQLite {
                fmt.Printf("Output written to: %s\n", outputPath)
        }
  }
